version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=fullstack_api
      - DATABASE_HOST=fullstack-postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pkg/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - fullstack

volumes:
  api:
  database_postgres:
networks:
  fullstack:
    driver: bridge